### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by jus61** [a-williams8427/PTWS#1]
`14:33:18 "PTWS - Loading Config"
14:33:18 "PTWS - Initialized"
14:33:18 Error in expression <llExtension _query);
(_result select 1) select 0>
14:33:18   Error position: <select 0>
14:33:18   Error Generic error in expression
14:33:18 File exile_server\code\ExileServer_system_database_query_insertSingle.sqf, line 16
14:33:20 "PTWS - Loading last saved date : [2016,8,22,15,35]"
14:33:20 "PTWS - Loading last saved weather : [0.176682,0,[0,0,0],[-0.109253,-0.673642,false],0.12368,0.1,0]"
14:33:20 Weather was forced to change
14:33:20 "PTWS - SaveDate Initialized"
14:33:20 "ExileServer - Job with handle 10006 added."
14:33:20 "PTWS - SaveWeather Initialized"
14:33:20 "ExileServer - Job with handle 10007 added."
14:33:20 "PTWS - TimeAcc Initialized"
14:33:20 "ExileServer - Job with handle 10008 added."
14:33:20 "PTWS - ControlWeather Initialized"
14:33:20 "PTWS - Time until next forecast:00:22:18"`

**Comment by a-williams8427** [comment]
That error occurs upon every restart because PTWS is trying to create a database entry that already exists, I've tried a few checks/conditions for it but none have worked so far. I'll try some new ones today.

**Comment by jus61** [comment]
THX

**Comment by a-williams8427** [comment]
New release has fixed the error, note that for those who already have a database entry for PTWS will still have the error for one more restart.
